# Generated by Django 4.2 on 2023-04-21 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 23, 52, 38, 376224), verbose_name='date account created'),
        ),
    ]
