# Generated by Django 4.2 on 2023-04-25 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customer_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='aod',
            field=models.DateField(default=datetime.date(2023, 4, 25), verbose_name='last accessed'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fixed_date',
            field=models.DateField(null=True, verbose_name='fixed date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='loan_date',
            field=models.DateField(null=True, verbose_name='loan date'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateTimeField(verbose_name='date of birth'),
        ),
    ]
