# Generated by Django 4.2 on 2023-04-21 17:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
                ('mobileno', models.CharField(max_length=10)),
                ('dob', models.DateTimeField(default=datetime.datetime(2023, 4, 21, 22, 47, 42, 842688), verbose_name='date account created')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aod', models.DateField(verbose_name='last accessed')),
                ('savings', models.IntegerField(default=0)),
                ('current', models.IntegerField(default=0)),
                ('fixed', models.IntegerField(default=0)),
                ('pin', models.IntegerField(max_length=4)),
                ('loan', models.IntegerField(default=0)),
                ('loan_date', models.DateField(verbose_name='loan date')),
                ('fixed_date', models.DateField(verbose_name='fixed date')),
                ('principle_amt', models.IntegerField(default=0)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customer')),
            ],
        ),
    ]
