# Generated by Django 4.2 on 2023-04-21 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customer_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 21, 23, 57, 55, 265152), verbose_name='date account created'),
        ),
    ]
